# Generated by Django 6.0.2 on 2026-02-09 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuoteSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("market", models.CharField(default="UK", max_length=10)),
                ("locale", models.CharField(default="en-GB", max_length=20)),
                ("currency", models.CharField(default="GBP", max_length=10)),
                ("pickup_entity_id", models.CharField(max_length=32)),
                ("pickup_datetime", models.DateTimeField()),
                ("dropoff_datetime", models.DateTimeField()),
                ("driver_age", models.PositiveSmallIntegerField()),
                ("included_agent_ids", models.JSONField(blank=True, null=True)),
                (
                    "session_token",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("READY", "Ready"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quote_searches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuoteOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agent_id", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "provider_name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("car_name", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "transmission",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("seats", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "total_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("currency", models.CharField(default="GBP", max_length=10)),
                ("deeplink_url", models.URLField(blank=True, null=True)),
                ("raw_json", models.JSONField()),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "search",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="pricing.quotesearch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FavoriteOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_offers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="pricing.quoteoffer",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "offer"), name="uniq_user_offer_fav"
                    )
                ],
            },
        ),
    ]
