# Generated by Django 5.2.11 on 2026-03-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0002_alter_favoriteoffer_id_alter_quoteoffer_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotesearch",
            name="return_entity_id",
            field=models.CharField(default="UNKONW", max_length=32),
            preserve_default=False,
        ),
    ]
